import { createFileRoute, Link } from '@tanstack/react-router'
import { motion } from 'framer-motion'
import { ArrowRight, Check, Clock, Heart, MapPin, Phone, ShieldCheck } from 'lucide-react'
import { FAQSection } from '~/components/FAQSection'
import { CTASection } from '~/components/CTASection'
import { HeroSlideshow } from '~/components/HeroSlideshow'
import { SectionHeader } from '~/components/SectionHeader'
import { TrustBar } from '~/components/TrustBar'
import { ReviewCard } from '~/components/ReviewCard'
import { JsonLd } from '~/components/JsonLd'
import { faqLd } from '~/lib/seo'
import { SERVICES } from '~/data/services'
import { AREAS } from '~/data/areas'
import { SITE } from '~/data/site'
import { reviews } from '~/data/reviews'
import { HERO_ALT, serviceImageUrl } from '~/data/images'
import { imageSrc } from '~/lib/asset-url'
import leaves from '~/assets/decorative/cleaning-leaves.png'
import type { FAQ } from '~/lib/types/page-types'

// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Homepage FAQ — replaced at build time.
const HOME_FAQS: FAQ[] = [
  {
    question: 'How quickly can you respond?',
    answer:
      'We reply within a business day to every quote request, and same-day for most service calls.',
  },
  {
    question: 'Are you licensed and insured?',
    answer: 'Yes — fully licensed and insured. Certificates available on request.',
  },
  {
    question: 'What areas do you serve?',
    answer:
      'See our Areas page for the full list. If you do not see your neighborhood, call us — we often travel for the right project.',
  },
]

export const Route = createFileRoute('/')({
  head: () => ({
    meta: [
      { title: `${SITE.name} — ${SITE.tagline}` },
      { name: 'description', content: SITE.tagline },
      { property: 'og:title', content: SITE.name },
      { property: 'og:description', content: SITE.tagline },
      { property: 'og:url', content: SITE.domain },
    ],
    links: [{ rel: 'canonical', href: SITE.domain }],
  }),
  component: HomePage,
})

function splitScriptAccent(heading: string): { lead: string; accent: string } {
  const words = heading.trim().split(/\s+/)
  if (words.length < 2) return { lead: '', accent: heading }
  return { lead: words.slice(0, -1).join(' '), accent: words.slice(-1).join('') }
}

function HomePage() {
  const heroParts = splitScriptAccent(SITE.hero.headline)
  const neighborhoodList = AREAS.slice(0, 8).map((a) => a.name).join(' · ')
  const previewServices = SERVICES.slice(0, 3)
  const previewReviews = reviews.slice(0, 6)

  return (
    <>
      <JsonLd data={faqLd(HOME_FAQS)} />

      {/* HERO */}
      <section className="relative overflow-hidden bg-gradient-to-b from-brand-50 via-white to-white">
        <img src={leaves} alt="" aria-hidden className="hidden md:block absolute -left-10 top-10 h-[80%] opacity-50 pointer-events-none select-none" />
        <img src={leaves} alt="" aria-hidden className="hidden md:block absolute -right-10 bottom-0 h-[60%] opacity-40 pointer-events-none select-none rotate-180" />

        <div className="container-x py-14 md:py-20 relative">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-16 items-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="lg:col-span-6"
            >
              <span className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-brand-700">
                <span className="h-px w-8 bg-brand-600" /> {SITE.hero.kicker}
              </span>
              <h1 className="mt-4">
                {heroParts.lead || SITE.hero.headline}
                {heroParts.lead && (
                  <>
                    <br />
                    <span className="font-script text-brand-600 text-[1.15em] block leading-[1.1] mt-1">
                      {heroParts.accent}
                    </span>
                  </>
                )}
              </h1>
              {SITE.hero.subheadline && (
                <p className="mt-3 font-display text-xl text-ink-700">
                  {SITE.hero.subheadline}
                </p>
              )}
              <p className="mt-6 text-lg text-ink-700 max-w-xl leading-relaxed">
                {SITE.hero.body}
              </p>
              <div className="mt-8 flex flex-wrap gap-3">
                <Link to="/contact" className="btn btn-lg btn-primary">
                  {SITE.hero.cta_primary_label} <ArrowRight className="h-4 w-4" />
                </Link>
                {/* NOTE: SITE.hero.cta_secondary_label exists for shape parity
                    with painter + scaffolder cleaning-english emit, but the
                    cleaning template's signature design uses a phone-dial button
                    as the secondary CTA (not a labelled link). Editing
                    hero.cta_secondary_label via AI editor will not produce a
                    visible change. To wire it in, replace this phone button OR
                    add a third button row. */}
                <a href={`tel:${SITE.phone}`} className="btn btn-lg btn-secondary">
                  <Phone className="h-4 w-4" /> {SITE.phoneDisplay}
                </a>
              </div>
              <ul className="mt-8 grid grid-cols-2 sm:flex sm:flex-wrap gap-x-6 gap-y-2 text-sm text-ink-700">
                {['Licensed & insured', 'Same-day quotes', 'Local team', '100% satisfaction'].map((t) => (
                  <li key={t} className="flex items-center gap-1.5">
                    <Check className="h-4 w-4 text-brand-600" /> {t}
                  </li>
                ))}
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, scale: 0.96 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.7, delay: 0.1 }}
              className="lg:col-span-6 relative"
            >
              <HeroSlideshow
                images={[{ src: imageSrc(SITE.hero.image_url), alt: HERO_ALT }]}
              />
            </motion.div>
          </div>
        </div>
      </section>

      {/* TAGLINE BAR */}
      {SITE.tagline && (
        <section className="bg-brand-900 text-white">
          <div className="container-x py-5 text-center">
            <p className="font-display text-lg md:text-xl">{SITE.tagline}</p>
          </div>
        </section>
      )}

      {/* LOCAL BAR */}
      {neighborhoodList && (
        <section className="bg-brand-50 border-y border-brand-100">
          <div className="container-x py-3 flex items-center gap-2 text-sm text-ink-700 overflow-x-auto whitespace-nowrap">
            <MapPin className="h-4 w-4 text-brand-600 shrink-0" />
            <span className="font-semibold text-ink-900 shrink-0">Now serving:</span>
            <span className="text-ink-500">{neighborhoodList}</span>
          </div>
        </section>
      )}

      {/* TRUST BAR */}
      <TrustBar
        items={[
          {
            icon: <ShieldCheck className="h-7 w-7" strokeWidth={1.8} />,
            title: 'Licensed & insured',
            description: 'Professional team with proper credentials and coverage.',
          },
          {
            icon: <Clock className="h-7 w-7" strokeWidth={1.8} />,
            title: 'Same-day quotes',
            description: "We reply within a business day, often the same day.",
          },
          {
            icon: <Heart className="h-7 w-7" strokeWidth={1.8} />,
            title: 'Local team',
            description: 'Familiar faces, familiar streets, real accountability.',
          },
        ]}
      />

      {/* SERVICES PREVIEW */}
      {previewServices.length > 0 && (
        <section className="bg-brand-50 border-y border-brand-100">
          <div className="container-x py-16 md:py-24">
            <SectionHeader
              label="Our services"
              heading="What we"
              scriptAccent="do"
              body="A focused list of services, done well."
            />
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {previewServices.map((s) => (
                <Link
                  key={s.slug}
                  to="/services/$slug"
                  params={{ slug: s.slug }}
                  className="card-stead overflow-hidden group hover:shadow-xl hover:-translate-y-1 transition-all"
                >
                  <div className="aspect-[4/3] overflow-hidden">
                    <img
                      src={serviceImageUrl(s.slug)}
                      alt={s.name}
                      loading="lazy"
                      width={800}
                      height={600}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    />
                  </div>
                  <div className="p-6">
                    <h3 className="text-xl">{s.name}</h3>
                    <p className="mt-2 text-ink-500">{s.short}</p>
                    <div className="mt-5 text-brand-600 font-semibold flex items-center gap-1 group-hover:gap-2 transition-all">
                      Explore <ArrowRight className="h-4 w-4" />
                    </div>
                  </div>
                </Link>
              ))}
            </div>
            {SERVICES.length > previewServices.length && (
              <div className="mt-8 text-center">
                <Link to="/services" className="btn btn-md btn-secondary">View all services →</Link>
              </div>
            )}
          </div>
        </section>
      )}

      {/* SERVICE AREAS */}
      {AREAS.length > 0 && (
        <section className="bg-white">
          <div className="container-x py-16 md:py-24">
            <SectionHeader
              label="Service areas"
              heading="Where we"
              scriptAccent="work"
              body="Local crews, familiar streets."
            />
            <div className="flex flex-wrap justify-center gap-2">
              {AREAS.map((a) => (
                <Link
                  key={a.slug}
                  to="/areas/$slug"
                  params={{ slug: a.slug }}
                  className="badge-pill bg-white border border-ink-100 text-ink-700 hover:border-brand-600 hover:text-brand-600 normal-case tracking-normal text-sm"
                >
                  <MapPin className="h-3.5 w-3.5" /> {a.name}
                </Link>
              ))}
            </div>
            <div className="mt-8 text-center">
              <Link to="/areas" className="btn btn-md btn-secondary">View all areas →</Link>
            </div>
          </div>
        </section>
      )}

      {/* REVIEWS */}
      {previewReviews.length > 0 && (
        <section className="bg-brand-50 border-y border-brand-100">
          <div className="container-x py-16 md:py-24">
            <SectionHeader
              label="Reviews"
              heading="What customers"
              scriptAccent="say"
            />
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
              {previewReviews.map((r) => (
                <ReviewCard key={r.id} review={r} />
              ))}
            </div>
            {reviews.length > previewReviews.length && (
              <div className="mt-8 text-center">
                <Link to="/reviews" className="btn btn-md btn-secondary">Read all reviews →</Link>
              </div>
            )}
          </div>
        </section>
      )}

      {/* FAQ */}
      <FAQSection faqs={HOME_FAQS} title="Frequently asked questions" />

      {/* CTA */}
      <CTASection
        title="Ready when you are."
        subtitle="Quote in 24 hours. No pressure."
      />
    </>
  )
}
