import { createFileRoute } from '@tanstack/react-router'
import { Hero } from '~/components/Hero'
import { TrustBadges } from '~/components/TrustBadges'
import { ServicesSection } from '~/components/ServicesSection'
import { AreasSection } from '~/components/AreasSection'
import { ReviewsSection } from '~/components/ReviewsSection'
import { FAQSection } from '~/components/FAQSection'
import { CTASection } from '~/components/CTASection'
import { JsonLd } from '~/components/JsonLd'
import { faqLd } from '~/lib/seo'
import { SERVICES } from '~/data/services'
import { AREAS } from '~/data/areas'
import { SITE } from '~/data/site'
import { HERO_IMAGE, HERO_ALT } from '~/data/images'
import type { FAQ } from '~/lib/types/page-types'

// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Homepage FAQ — replaced at build time.
const HOME_FAQS: FAQ[] = [
  {
    question: 'How quickly can you respond?',
    answer:
      'We reply within a business day to every quote request, and same-day for most service calls.',
  },
  {
    question: 'Are you licensed and insured?',
    answer: 'Yes — fully licensed and insured. Certificates available on request.',
  },
  {
    question: 'What areas do you serve?',
    answer:
      'See our Areas page for the full list. If you do not see your neighborhood, call us — we often travel for the right project.',
  },
]

export const Route = createFileRoute('/')({
  head: () => ({
    meta: [
      { title: `${SITE.name} — ${SITE.tagline}` },
      { name: 'description', content: SITE.tagline },
      { property: 'og:title', content: SITE.name },
      { property: 'og:description', content: SITE.tagline },
      { property: 'og:url', content: SITE.domain },
    ],
    links: [{ rel: 'canonical', href: SITE.domain }],
  }),
  component: HomePage,
})

function HomePage() {
  return (
    <>
      <JsonLd data={faqLd(HOME_FAQS)} />
      <Hero
        headline={SITE.name}
        subheadline={SITE.tagline}
        ctaPrimary={{ label: 'Get a quote', href: '/contact' }}
        ctaSecondary={{
          label: `Call ${SITE.phoneDisplay}`,
          href: `tel:${SITE.phone}`,
        }}
        heroImage={{ src: `/images/${HERO_IMAGE}`, alt: HERO_ALT }}
      />
      <TrustBadges items={['Licensed & insured', 'Same-day quotes', 'Local team']} />
      <ServicesSection
        heading="What we do"
        intro="A short list of focused services, done well."
        services={SERVICES}
      />
      <AreasSection
        heading="Where we work"
        intro="Local crews, familiar streets."
        areas={AREAS}
      />
      <ReviewsSection heading="What customers say" />
      <FAQSection faqs={HOME_FAQS} title="Frequently asked questions" />
      <CTASection
        title="Ready when you are."
        subtitle="Quote in 24 hours. No pressure."
      />
    </>
  )
}
