import { createFileRoute } from '@tanstack/react-router'
import { JsonLd } from '~/components/JsonLd'
import { faqLd } from '~/lib/seo'
import { SITE } from '~/data/site'
import type { FAQ } from '~/lib/types/page-types'
import { HOMEPAGE_LAYOUT, type LayoutBlock } from '~/data/layout'
import { HeroBlock } from '~/components/blocks/HeroBlock'
import { TaglineBarBlock } from '~/components/blocks/TaglineBarBlock'
import { LocalBarBlock } from '~/components/blocks/LocalBarBlock'
import { TrustBarBlock } from '~/components/blocks/TrustBarBlock'
import { ServicesPreviewBlock } from '~/components/blocks/ServicesPreviewBlock'
import { ServiceAreasBlock } from '~/components/blocks/ServiceAreasBlock'
import { ReviewsBlock } from '~/components/blocks/ReviewsBlock'
import { FaqBlock } from '~/components/blocks/FaqBlock'
import { CtaBlock } from '~/components/blocks/CtaBlock'

// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Homepage FAQ — replaced at build time.
const HOME_FAQS: FAQ[] = [
  {
    question: 'How quickly can you respond?',
    answer:
      'We reply within a business day to every quote request, and same-day for most service calls.',
  },
  {
    question: 'Are you licensed and insured?',
    answer: 'Yes — fully licensed and insured. Certificates available on request.',
  },
  {
    question: 'What areas do you serve?',
    answer:
      'See our Areas page for the full list. If you do not see your neighborhood, call us — we often travel for the right project.',
  },
]

export const Route = createFileRoute('/')({
  head: () => ({
    meta: [
      { title: `${SITE.name} — ${SITE.tagline}` },
      { name: 'description', content: SITE.tagline },
      { property: 'og:title', content: SITE.name },
      { property: 'og:description', content: SITE.tagline },
      { property: 'og:url', content: SITE.domain },
    ],
    links: [{ rel: 'canonical', href: SITE.domain }],
  }),
  component: HomePage,
})

// Map a layout block to its rendered section. Order/presence are driven by
// HOMEPAGE_LAYOUT (src/data/layout.ts); each block owns its own markup +
// data-conditional auto-omit. The faq block receives HOME_FAQS from this route
// (the scaffolder-target constant above).
function renderBlock(block: LayoutBlock) {
  switch (block.type) {
    case 'hero':
      return (
        <HeroBlock
          key="hero"
          trustItems={block.params?.trustItems as string[] | undefined}
          decorativeAsset={block.params?.decorativeAsset as string | undefined}
        />
      )
    case 'taglineBar':
      return <TaglineBarBlock key="taglineBar" />
    case 'localBar':
      return (
        <LocalBarBlock
          key="localBar"
          label={block.params?.label as string | undefined}
        />
      )
    case 'trustBar':
      return <TrustBarBlock key="trustBar" />
    case 'servicesPreview':
      return (
        <ServicesPreviewBlock
          key="servicesPreview"
          label={block.params?.label as string | undefined}
          heading={block.params?.heading as string | undefined}
          scriptAccent={block.params?.scriptAccent as string | undefined}
          body={block.params?.body as string | undefined}
          exploreLabel={block.params?.exploreLabel as string | undefined}
          moreLink={block.params?.moreLink as string | undefined}
        />
      )
    case 'serviceAreas':
      return (
        <ServiceAreasBlock
          key="serviceAreas"
          label={block.params?.label as string | undefined}
          heading={block.params?.heading as string | undefined}
          scriptAccent={block.params?.scriptAccent as string | undefined}
          body={block.params?.body as string | undefined}
          moreLink={block.params?.moreLink as string | undefined}
        />
      )
    case 'reviews':
      return (
        <ReviewsBlock
          key="reviews"
          label={block.params?.label as string | undefined}
          heading={block.params?.heading as string | undefined}
          scriptAccent={block.params?.scriptAccent as string | undefined}
          moreLink={block.params?.moreLink as string | undefined}
        />
      )
    case 'faq':
      return (
        <FaqBlock
          key="faq"
          faqs={HOME_FAQS}
          title={block.params?.title as string | undefined}
        />
      )
    case 'cta':
      return (
        <CtaBlock
          key="cta"
          title={block.params?.title as string | undefined}
          subtitle={block.params?.subtitle as string | undefined}
        />
      )
  }
}

function HomePage() {
  return (
    <>
      <JsonLd data={faqLd(HOME_FAQS)} />
      {HOMEPAGE_LAYOUT.map(renderBlock)}
    </>
  )
}
