/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AreasIndexRouteImport } from './routes/areas.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as InfoSlugRouteImport } from './routes/info.$slug'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasIndexRoute = AreasIndexRouteImport.update({
  id: '/areas/',
  path: '/areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoSlugRoute = InfoSlugRouteImport.update({
  id: '/info/$slug',
  path: '/info/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/info/$slug': typeof InfoSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/info/$slug': typeof InfoSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas': typeof AreasIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/info/$slug': typeof InfoSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/areas/': typeof AreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/pricing'
    | '/quote'
    | '/reviews'
    | '/areas/$slug'
    | '/info/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/areas/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/pricing'
    | '/quote'
    | '/reviews'
    | '/areas/$slug'
    | '/info/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/areas'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/contact'
    | '/pricing'
    | '/quote'
    | '/reviews'
    | '/areas/$slug'
    | '/info/$slug'
    | '/p/$slug'
    | '/services/$slug'
    | '/areas/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  AreasSlugRoute: typeof AreasSlugRoute
  InfoSlugRoute: typeof InfoSlugRoute
  PSlugRoute: typeof PSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AreasIndexRoute: typeof AreasIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/': {
      id: '/areas/'
      path: '/areas'
      fullPath: '/areas/'
      preLoaderRoute: typeof AreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$slug': {
      id: '/info/$slug'
      path: '/info/$slug'
      fullPath: '/info/$slug'
      preLoaderRoute: typeof InfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  AreasSlugRoute: AreasSlugRoute,
  InfoSlugRoute: InfoSlugRoute,
  PSlugRoute: PSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AreasIndexRoute: AreasIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
