import type { AreaRef, ServiceAreaPageData } from '~/lib/types/page-types'

// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.

export const AREAS: AreaRef[] = [
  {
    slug: 'sample-area',
    name: 'Sample Area',
    tier: 'primary',
  },
]

export const serviceAreasData: Record<string, ServiceAreaPageData> = {}
