import type { CustomPageRef, CustomPageData } from '~/lib/types/page-types'

// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Populated from design_dna.customPages (Phase 2 — add/remove whole pages). Empty here
// so the reference (and any build with no custom pages) ships byte-identical: no /p/$slug
// pages resolve and no custom nav links render.

export const CUSTOM_PAGES: CustomPageRef[] = []

export const customPagesData: Record<string, CustomPageData> = {}
