import type { PageGallery } from '~/lib/types/page-types'

// AUTO-GENERATED BY FACTORY SCAFFOLDER from design_dna.galleries — DO NOT EDIT.
// The owner's own gallery per page (ZB-147): photos in their order, the cover, the layout, hidden.
// Empty here: every page's gallery falls back to its category (galleryFor in lib/galleries.ts).
export const GALLERIES: Record<string, PageGallery> = {}
