// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Image filenames live in /public/images/*.webp. The scaffolder writes the
// public/ overlay AND emits this file with the slug-to-filename maps.

// HERO_IMAGE moved to SITE.hero.image_url (src/data/site.ts) so the hero image
// is editor-editable per field. Used here as the service/area fallback.
import type { CSSProperties } from 'react'
import { SITE } from '~/data/site'
import { imageSrc } from '~/lib/asset-url'
import { focusPoint } from '~/lib/hero-focus'

export const HERO_ALT = 'Reference hero image'

// Industry-anchored editorial photo (distinct from the hero). "" in the template → scaffolder overwrites.
export const EDITORIAL_IMAGE = ''

export const AREA_IMAGES: Record<string, string> = {}
export const AREA_ALT: Record<string, string> = {}
export const SERVICE_IMAGES: Record<string, string> = {}
// The owner's OWN service photos (set on the service, never stock): the layouts that carry no stock imagery show these.
export const OWNER_SERVICE_IMAGES: Record<string, string> = {}
// a service photo has a focal point, 2026-09-30: "x% y%" per service slug, set by the owner by asking ("show more of the top"),
// the same value shape as SITE.hero.image_focus; "" or absent = no point (the portrait rule in lib/hero-focus-runtime.ts decides).
export const SERVICE_IMAGE_FOCUS: Record<string, string> = {}
// Per-info-page images, spread across the editorial + service pool (scaffolder-emitted).
export const PAGE_IMAGES: Record<string, string> = {}

export function areaImage(slug: string): string {
  return AREA_IMAGES[slug] ?? SITE.hero.image_url
}

export function areaImageUrl(slug: string): string {
  return imageSrc(areaImage(slug))
}

export function areaAlt(slug: string): string {
  return AREA_ALT[slug] ?? HERO_ALT
}

export function serviceImage(slug: string): string {
  return SERVICE_IMAGES[slug] ?? SITE.hero.image_url
}

export function serviceImageUrl(slug: string): string {
  return imageSrc(serviceImage(slug))
}

// The owner's own photo for a service, or null: a picture-less layout (icon tiles, the list) shows it when it exists.
export function ownerServiceImageUrl(slug: string): string | null {
  const f = OWNER_SERVICE_IMAGES[slug]
  return f ? imageSrc(f) : null
}

// The owner's focal point for a service photo, or null: every block that draws the photo applies it as object-position.
export function serviceImageFocus(slug: string): string | null {
  return focusPoint(SERVICE_IMAGE_FOCUS[slug])
}

export function serviceImageFocusStyle(slug: string): CSSProperties | undefined {
  const f = serviceImageFocus(slug)
  return f ? { objectPosition: f } : undefined
}

export function ogImageForService(slug: string): string {
  return imageSrc(serviceImage(slug))
}

export function ogImageForArea(slug: string): string {
  return imageSrc(areaImage(slug))
}

export function pageImage(slug: string): string {
  return PAGE_IMAGES[slug] ?? (EDITORIAL_IMAGE || SITE.hero.image_url)
}

export function pageImageUrl(slug: string): string {
  return imageSrc(pageImage(slug))
}

// True only when a DISTINCT (non-hero) page image exists — the info banner renders only then, so
// thin builds stay text-forward instead of repeating the hero.
export function hasPageImage(slug: string): boolean {
  return !!(PAGE_IMAGES[slug] || EDITORIAL_IMAGE)
}
