// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Image filenames live in /public/images/*.webp. The scaffolder writes the
// public/ overlay AND emits this file with the slug-to-filename maps.

// HERO_IMAGE moved to SITE.hero.image_url (src/data/site.ts) so the hero image
// is editor-editable per field. Used here as the service/area fallback.
import { SITE } from '~/data/site'
import { imageSrc } from '~/lib/asset-url'

export const HERO_ALT = 'Reference hero image'

export const AREA_IMAGES: Record<string, string> = {}
export const AREA_ALT: Record<string, string> = {}
export const SERVICE_IMAGES: Record<string, string> = {}

export function areaImage(slug: string): string {
  return AREA_IMAGES[slug] ?? SITE.hero.image_url
}

export function areaImageUrl(slug: string): string {
  return imageSrc(areaImage(slug))
}

export function areaAlt(slug: string): string {
  return AREA_ALT[slug] ?? HERO_ALT
}

export function serviceImage(slug: string): string {
  return SERVICE_IMAGES[slug] ?? SITE.hero.image_url
}

export function serviceImageUrl(slug: string): string {
  return imageSrc(serviceImage(slug))
}

export function ogImageForService(slug: string): string {
  return imageSrc(serviceImage(slug))
}

export function ogImageForArea(slug: string): string {
  return imageSrc(areaImage(slug))
}
