// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Image filenames live in /public/images/*.webp. The scaffolder writes the
// public/ overlay AND emits this file with the slug-to-filename maps.

export const HERO_IMAGE = 'hero-reference.webp'
export const HERO_ALT = 'Reference hero image'

export const AREA_IMAGES: Record<string, string> = {}
export const AREA_ALT: Record<string, string> = {}
export const SERVICE_IMAGES: Record<string, string> = {}

export function areaImage(slug: string): string {
  return AREA_IMAGES[slug] ?? HERO_IMAGE
}

export function areaImageUrl(slug: string): string {
  return `/images/${areaImage(slug)}`
}

export function areaAlt(slug: string): string {
  return AREA_ALT[slug] ?? HERO_ALT
}

export function serviceImage(slug: string): string {
  return SERVICE_IMAGES[slug] ?? HERO_IMAGE
}

export function serviceImageUrl(slug: string): string {
  return `/images/${serviceImage(slug)}`
}

export function ogImageForService(slug: string): string {
  return `/images/${serviceImage(slug)}`
}

export function ogImageForArea(slug: string): string {
  return `/images/${areaImage(slug)}`
}
