import type { InfoPageData, InfoPageRef } from '~/lib/types/page-types'

// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.

export const INFO_PAGES: InfoPageRef[] = []

export const infoPagesData: Record<string, InfoPageData> = {}
