import type { ServicePageData, ServiceRef } from '~/lib/types/page-types'

// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// The scaffolder replaces this entire file per build.
//
// ★★★ FROZEN, AND THAT IS NOT DECORATION. Emit-time correctness proved insufficient: on
// 2026-08-30 the scaffolder emitted four correct services for two businesses and a dev-only
// route then did `SERVICES.length = 0; SERVICES.push(…)` at MODULE LOAD, so both sites shipped
// advertising six services their owners never entered. Merely being in the bundle was enough —
// no route had to be visited. Object.freeze turns that from a silent overwrite into a throw.
export const SERVICES: ServiceRef[] = Object.freeze([
  {
    // Every entry carries a real catalog uuid; `id` is required on ServiceRef for that reason.
    id: '00000000-0000-0000-0000-000000000000',
    slug: 'sample-service',
    name: 'Sample Service',
    // Heading form of `name`; identical here because the placeholder is already title case.
    displayName: 'Sample Service',
    short: 'Placeholder service entry.',
    tagline: 'Replaced by factory build.',
  },
]) as ServiceRef[]

export const servicesData: Record<string, ServicePageData> = {}
