import type { ServicePageData, ServiceRef } from '~/lib/types/page-types'

// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// The scaffolder replaces this entire file per build.

export const SERVICES: ServiceRef[] = [
  {
    slug: 'sample-service',
    name: 'Sample Service',
    short: 'Placeholder service entry.',
    tagline: 'Replaced by factory build.',
  },
]

export const servicesData: Record<string, ServicePageData> = {}
