// AUTO-GENERATED BY FACTORY SCAFFOLDER, DO NOT EDIT.
// Personalized at build time from intake_json.business.* fields.
// The static tail (SUPABASE_ENDPOINT, etc.) is preserved across rebuilds.

export const SITE = {
  name: 'Reference Site',
  logo_url: '',
  domain: 'https://example.com',
  phone: '+15555550100',
  phoneDisplay: '(555) 555-0100',
  email: 'hello@example.com',
  address: {
    street: '',
    city: '',
    state: '',
    zip: '',
  },
  hours: 'Mon–Fri 8am–6pm',
  tagline: 'Reliable. Professional. Consistent.',
  // Meta/OG description. The scaffolder emits a real, honest per-site value; this
  // seed keeps the reference project type-checking + rendering standalone. Read by
  // __root (falling back to SITE.name), decoupled from `tagline` so the tagline bar
  // can be empty without emptying the site's <meta description>.
  description: 'Reliable, professional service you can count on.',
  // Structured hero copy. The homepage (routes/index.tsx) reads every field
  // below instead of JSX literals, so editor-api can edit hero copy per field
  // and the scaffolder's cleaning-english emit (emit-vite/site-config.ts) maps
  // 1:1 onto this shape. Mirrors the painter template (factory-reference-vite-
  // painter). image_url is a bare filename resolved via imageSrc() (lib/asset-
  // url) → /images/<file>; full URLs pass through unchanged.
  hero: {
    kicker: 'Cleaning · Cincinnati · Est. 2014',
    headline: 'The careful kind of cleaning.',
    subheadline: 'For Cincinnati homes that deserve it.',
    body: 'Recurring, deep, and move-out cleaning, handled by a careful team and backed by a spotless-home guarantee.',
    cta_primary_label: 'Request a quote',
    cta_secondary_label: 'Browse services',
    image_url: 'hero-reference.webp',
  },
  // De-leaked marketing prose (Phase 1). The scaffolder emits vertical-varied
  // values here (emit-vite/site-config.ts); /about, /pricing, and the homepage
  // FAQ read these instead of hardcoded literals. Seed values below are the
  // reference repo's own placeholders, overwritten on every build.
  about:
    'We treat every home like our own, a careful team, a clear checklist, and a finish backed by our satisfaction guarantee.',
  pricing:
    'Every job is quoted up front based on scope and condition, no hourly meter, no surprises. The price you approve is the price you pay.',
  homeFaqs: [
    {
      question: 'How quickly can you schedule?',
      answer:
        'Most homes can be booked within a few days, and recurring slots stay open for ongoing clients.',
    },
    {
      question: 'Are you licensed and insured?',
      answer:
        'Ask us about our background and coverage, we’re glad to share the details so you feel comfortable before we start.',
    },
    {
      question: 'Do I need to provide supplies?',
      answer: 'No, our team brings everything needed for a thorough, careful job.',
    },
  ],
  social: {
    instagram: '',
    facebook: '',
    yelp: '',
    google: '',
  },
  // Homepage identity copy promoted out of block JSX into DATA (variant blocks read
  // these). Seed placeholders; the scaffolder's emit-vite/site-config overwrites them
  // per build when a vertical provides copy.homeServices / copy.homeCta.
  homeServices: {
    label: 'What we do',
    heading: 'Services',
    body: 'A focused set of services, done well.',
  },
  homeCta: {
    title: 'Ready to get started?',
    subtitle: 'Tell us what you need and we’ll take it from there.',
  },
  // Section identity copy for the remapped serviceAreas/reviews variants + the global
  // header CTA. Variant components read these (cast + ?? neutral fallback) so character
  // sections carry the VERTICAL's copy when authored, and a vertical-NEUTRAL generic when
  // not, never another vertical's baked demo copy. Overwritten per build when a vertical
  // provides copy.homeAreas / copy.homeReviews / copy.headerCtaLabel.
  homeAreas: {
    label: 'Service areas',
    heading: 'Where we',
    scriptAccent: 'work',
    body: 'Local coverage, close to home.',
  },
  homeReviews: {
    label: 'Reviews',
    heading: 'What customers',
    scriptAccent: 'say',
  },
  headerCtaLabel: 'Get a free quote',
}

export const BUSINESS_ID = '00000000-0000-0000-0000-000000000000'
/**
 * ★★ THE SITE'S OWN WRITE KEY — opaque, revocable, and NOT derivable from anything on the page.
 * Empty here and in any build made before the trigger supplies one; the beacon and the lead form
 * both fall back to BUSINESS_ID when it is empty, so an unkeyed build behaves exactly as it does
 * today. ⚠️ A published site cannot receive a key without being rebuilt, and rebuilding overwrites
 * the owner's edits — so already-live sites keep the fallback until they are next built, by design.
 */
export const SITE_KEY = ''
export const SUPABASE_ENDPOINT =
  'https://nldfnnyhrovytkuvtuby.supabase.co/functions/v1/handle-website-lead'
export const SITE_LANGUAGE: 'en' | 'es' = 'en'

// Supabase project constants (static tail, preserved across rebuilds, same
// project for every business). SUPABASE_URL is the REST/functions base; the anon
// key is a PUBLIC JWT (role "anon") already embedded in every glow client bundle,
// safe to ship in a static site. Used by the native BookingWizardBlock to read the
// business's bookable services + weekly availability (anon-readable via RLS) and to
// POST the public create-booking edge function. NOT used for the lead form (that
// posts SUPABASE_ENDPOINT with no auth header).
export const SUPABASE_URL = 'https://nldfnnyhrovytkuvtuby.supabase.co'
export const SUPABASE_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZGZubnlocm92eXRrdXZ0dWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTcyMjYsImV4cCI6MjA3NDkzMzIyNn0.X40zQQ1dkkSfggxjhAkMOqwKQa43jIKQNNLjtD9jpU0'

// Native self-service booking config. `enabled` gates the on-page BookingWizardBlock
// + the header/hero "Book Now" anchor; the scaffolder emits `true` ONLY for
// solo-appointment business types where the single-resource scheduler is correct
// (see character-presets bookingDefaultForType). `timezone` is the business's IANA
// zone (create-booking converts the picked wall-clock time → UTC using it). Seed =
// disabled so the reference project renders standalone with no booking section.
export const BOOKING: { enabled: boolean; timezone: string } = {
  enabled: false,
  timezone: 'America/New_York',
}
