// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Personalized at build time from intake_json.business.* fields.
// The static tail (SUPABASE_ENDPOINT, etc.) is preserved across rebuilds.

export const SITE = {
  name: 'Reference Site',
  domain: 'https://example.com',
  phone: '+15555550100',
  phoneDisplay: '(555) 555-0100',
  email: 'hello@example.com',
  address: {
    street: '',
    city: '',
    state: '',
    zip: '',
  },
  hours: 'Mon–Fri 8am–6pm',
  tagline: 'Reliable. Professional. Consistent.',
  social: {
    instagram: '',
    facebook: '',
    yelp: '',
    google: '',
  },
}

export const BUSINESS_ID = '00000000-0000-0000-0000-000000000000'
export const SUPABASE_ENDPOINT =
  'https://nldfnnyhrovytkuvtuby.supabase.co/functions/v1/handle-website-lead'
export const SITE_LANGUAGE: 'en' | 'es' = 'en'
