// AUTO-GENERATED BY FACTORY SCAFFOLDER — DO NOT EDIT.
// Personalized at build time from intake_json.business.* fields.
// The static tail (SUPABASE_ENDPOINT, etc.) is preserved across rebuilds.

export const SITE = {
  name: 'Reference Site',
  logo_url: '',
  domain: 'https://example.com',
  phone: '+15555550100',
  phoneDisplay: '(555) 555-0100',
  email: 'hello@example.com',
  address: {
    street: '',
    city: '',
    state: '',
    zip: '',
  },
  hours: 'Mon–Fri 8am–6pm',
  tagline: 'Reliable. Professional. Consistent.',
  // Structured hero copy. The homepage (routes/index.tsx) reads every field
  // below instead of JSX literals, so editor-api can edit hero copy per field
  // and the scaffolder's cleaning-english emit (emit-vite/site-config.ts) maps
  // 1:1 onto this shape. Mirrors the painter template (factory-reference-vite-
  // painter). image_url is a bare filename resolved via imageSrc() (lib/asset-
  // url) → /images/<file>; full URLs pass through unchanged.
  hero: {
    kicker: 'Cleaning · Cincinnati · Est. 2014',
    headline: 'The careful kind of cleaning.',
    subheadline: 'For Cincinnati homes that deserve it.',
    body: 'Recurring, deep, and move-out cleaning — handled by a careful team and backed by a spotless-home guarantee.',
    cta_primary_label: 'Request a quote',
    cta_secondary_label: 'Browse services',
    image_url: 'hero-reference.webp',
  },
  // De-leaked marketing prose (Phase 1). The scaffolder emits vertical-varied
  // values here (emit-vite/site-config.ts); /about, /pricing, and the homepage
  // FAQ read these instead of hardcoded literals. Seed values below are the
  // reference repo's own placeholders, overwritten on every build.
  about:
    'We treat every home like our own — a careful team, a clear checklist, and a finish backed by our satisfaction guarantee.',
  pricing:
    'Every job is quoted up front based on scope and condition — no hourly meter, no surprises. The price you approve is the price you pay.',
  homeFaqs: [
    {
      question: 'How quickly can you schedule?',
      answer:
        'Most homes can be booked within a few days, and recurring slots stay open for ongoing clients.',
    },
    {
      question: 'Are you licensed and insured?',
      answer:
        'Ask us about our background and coverage — we’re glad to share the details so you feel comfortable before we start.',
    },
    {
      question: 'Do I need to provide supplies?',
      answer: 'No — our team brings everything needed for a thorough, careful job.',
    },
  ],
  social: {
    instagram: '',
    facebook: '',
    yelp: '',
    google: '',
  },
  // Homepage identity copy promoted out of block JSX into DATA (variant blocks read
  // these). Seed placeholders; the scaffolder's emit-vite/site-config overwrites them
  // per build when a vertical provides copy.homeServices / copy.homeCta.
  homeServices: {
    label: 'What we do',
    heading: 'Services',
    body: 'A focused set of services, done well.',
  },
  homeCta: {
    title: 'Ready to get started?',
    subtitle: 'Tell us what you need and we’ll take it from there.',
  },
  // Section identity copy for the remapped serviceAreas/reviews variants + the global
  // header CTA. Variant components read these (cast + ?? neutral fallback) so character
  // sections carry the VERTICAL's copy when authored, and a vertical-NEUTRAL generic when
  // not — never another vertical's baked demo copy. Overwritten per build when a vertical
  // provides copy.homeAreas / copy.homeReviews / copy.headerCtaLabel.
  homeAreas: {
    label: 'Service areas',
    heading: 'Where we',
    scriptAccent: 'work',
    body: 'Local coverage, close to home.',
  },
  homeReviews: {
    label: 'Reviews',
    heading: 'What customers',
    scriptAccent: 'say',
  },
  headerCtaLabel: 'Get a free quote',
}

export const BUSINESS_ID = '00000000-0000-0000-0000-000000000000'
export const SUPABASE_ENDPOINT =
  'https://nldfnnyhrovytkuvtuby.supabase.co/functions/v1/handle-website-lead'
export const SITE_LANGUAGE: 'en' | 'es' = 'en'
